# Generated by Django 5.1.1 on 2024-12-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/users/', verbose_name='Қолданушы суреті'),
        ),
    ]
