# Generated by Django 5.1.1 on 2024-12-25 06:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Атауы')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Кілттік сөз')),
            ],
            options={
                'verbose_name': 'Интерфейс',
                'verbose_name_plural': 'Интерфейстер',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_body', models.TextField(verbose_name='Берілген сұрақ')),
                ('question_type', models.CharField(choices=[('simple', 'Бір жауапты')], default='simple', max_length=128, verbose_name='Сұрақ түрі')),
            ],
            options={
                'verbose_name': 'Сұрақ',
                'verbose_name_plural': 'Сұрақтар',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_body', models.TextField(verbose_name='Нұсқаның мәтіні')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Дұрыс жауап')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Балл')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='workspace.question', verbose_name='Сұрақ')),
            ],
            options={
                'verbose_name': 'Нұсқа жауабы',
                'verbose_name_plural': 'Нұсқа жауаптары',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Тақырыбы')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='workspace/quiz/posters/', verbose_name='Постер')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Анықтамасы')),
                ('max_score', models.PositiveSmallIntegerField(default=0, verbose_name='Макс. балл')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='workspace.interface', verbose_name='Интерфейс')),
            ],
            options={
                'verbose_name': 'Ойын тесті',
                'verbose_name_plural': 'Ойын тесттері',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='workspace.quiz', verbose_name='Ойын тесті'),
        ),
        migrations.CreateModel(
            name='QuizControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='workspace/qr_codes/', verbose_name='QR код')),
                ('status', models.CharField(choices=[('started', 'Басталды'), ('finished', 'Аяқталды')], default='started', max_length=128, verbose_name='Статус')),
                ('date_started', models.DateTimeField(verbose_name='Басталған уақыт')),
                ('date_finished', models.DateTimeField(blank=True, null=True, verbose_name='Аяқталған уақыт')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_controls', to='workspace.quiz', verbose_name='Ойын тесті')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_controls', to=settings.AUTH_USER_MODEL, verbose_name='Қолданушы')),
            ],
            options={
                'verbose_name': 'Тест бақылау',
                'verbose_name_plural': 'Тест бақылаулар',
            },
        ),
        migrations.CreateModel(
            name='UserQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, verbose_name='Қолданушы аты-жөні')),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Сессия ID')),
                ('total_score', models.PositiveSmallIntegerField(default=0, verbose_name='Жалпы балл')),
                ('status', models.CharField(choices=[('started', 'Басталды'), ('finished', 'Аяқталды')], default='started', max_length=128, verbose_name='Статус')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quizzes', to='workspace.quiz', verbose_name='Ойын тесті')),
                ('quiz_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quizzes', to='workspace.quizcontrol', verbose_name='Тест бақылау')),
            ],
            options={
                'verbose_name': 'Қолданушының тесті',
                'verbose_name_plural': 'Қолданушылардың тесттері',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Балл')),
                ('answers', models.ManyToManyField(to='workspace.option', verbose_name='Жауаптар')),
                ('user_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='workspace.userquiz', verbose_name='Қолданушының тесті')),
            ],
            options={
                'verbose_name': 'Қолданушының жауабы',
                'verbose_name_plural': 'Қолданушылардың жауаптары',
            },
        ),
    ]
