# Generated by Django 5.1.1 on 2024-11-16 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_body', models.TextField(verbose_name='Question body')),
                ('question_type', models.CharField(choices=[('SIMPLE', 'Simple')], default='SIMPLE', max_length=128, verbose_name='Question type')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Slug')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='workspace/quiz/posters/', verbose_name='Poster')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('interface', models.CharField(choices=[('DEFAULT', 'Default')], default='DEFAULT', max_length=128, verbose_name='Interface')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_body', models.TextField(verbose_name='Option body')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is correct answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_options', to='workspace.question', verbose_name='Question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='workspace.quiz', verbose_name='Quiz'),
        ),
        migrations.CreateModel(
            name='QuizControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=128, verbose_name='Status')),
                ('date_started', models.DateTimeField(verbose_name='Date started')),
                ('date_finished', models.DateTimeField(verbose_name='Date finished')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_quiz_controls', to='workspace.quiz', verbose_name='Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_quiz_controls', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'QuizControl',
                'verbose_name_plural': 'QuizControls',
            },
        ),
        migrations.CreateModel(
            name='UserQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, verbose_name='Username')),
                ('total_score', models.PositiveSmallIntegerField(default=0, verbose_name='Total score')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_user_quizzes', to='workspace.quiz', verbose_name='Quiz')),
                ('quiz_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_user_quizzes', to='workspace.quizcontrol', verbose_name='QuizControl')),
            ],
            options={
                'verbose_name': 'UserQuiz',
                'verbose_name_plural': 'UserQuizzes',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Answer score')),
                ('answers', models.ManyToManyField(to='workspace.option', verbose_name='Answer')),
                ('user_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uq_answers', to='workspace.userquiz', verbose_name='UserQuiz')),
            ],
            options={
                'verbose_name': 'UserAnswer',
                'verbose_name_plural': 'UserAnswers',
            },
        ),
    ]
