# Generated by Django 5.1.1 on 2024-11-16 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='slug',
        ),
    ]
