# Generated by Django 5.1.1 on 2024-12-25 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_interface_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interface',
            options={'ordering': ('order',), 'verbose_name': 'Интерфейс', 'verbose_name_plural': 'Интерфейстер'},
        ),
    ]
