# Generated by Django 5.1.1 on 2024-11-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_remove_quiz_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizcontrol',
            name='status',
            field=models.BooleanField(choices=[('STARTED', 'Started'), ('PROCESS', 'Process'), ('FINISHED', 'Finished')], default='STARTED', max_length=128, verbose_name='Status'),
        ),
    ]
