# Generated by Django 5.1.1 on 2024-11-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_alter_quizcontrol_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizcontrol',
            name='status',
            field=models.CharField(choices=[('STARTED', 'Started'), ('PROCESS', 'Process'), ('FINISHED', 'Finished')], default='STARTED', max_length=128, verbose_name='Status'),
        ),
    ]
