# Generated by Django 5.1.1 on 2024-12-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_alter_interface_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Реттілік номері'),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Реттілік номері'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Реттілік номері'),
        ),
    ]
