# Generated by Django 5.1.1 on 2024-11-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_alter_quizcontrol_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizcontrol',
            name='date_finished',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date finished'),
        ),
    ]
