# Generated by Django 5.1.1 on 2024-11-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_alter_quizcontrol_date_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Max score'),
        ),
    ]
