# Generated by Django 5.1.1 on 2025-01-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_alter_question_options_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Атауы')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Кілттік сөз')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Реттілік номері')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категориялар',
                'ordering': ('order',),
            },
        ),
    ]
