# Generated by Django 5.1.1 on 2024-11-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_quiz_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcontrol',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='workspaces/qr_codes/', verbose_name='QR Code'),
        ),
        migrations.AlterField(
            model_name='quizcontrol',
            name='status',
            field=models.CharField(choices=[('STARTED', 'Started'), ('FINISHED', 'Finished')], default='STARTED', max_length=128, verbose_name='Status'),
        ),
    ]
