# Generated by Django 5.1.1 on 2024-11-27 19:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0007_quizcontrol_qr_code_alter_quizcontrol_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Session ID'),
        ),
    ]
