# Generated by Django 5.1.1 on 2024-11-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0008_userquiz_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='score',
        ),
        migrations.AddField(
            model_name='option',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Score'),
        ),
    ]
