# Generated by Django 5.1.1 on 2024-11-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0009_remove_useranswer_score_option_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Score'),
        ),
    ]
