# Generated by Django 5.1.1 on 2024-11-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0010_useranswer_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='status',
            field=models.CharField(choices=[('STARTED', 'Started'), ('FINISHED', 'Finished')], default='STARTED', max_length=128, verbose_name='Status'),
        ),
    ]
