# Generated by Django 5.1.1 on 2024-11-29 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0011_userquiz_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Option', 'verbose_name_plural': 'Options'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
    ]
