# Generated by Django 5.1.1 on 2024-12-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0013_alter_quiz_interface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizcontrol',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='workspace/qr_codes/', verbose_name='QR Code'),
        ),
    ]
