# Generated by Django 5.1.1 on 2024-12-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0014_alter_quizcontrol_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='x_position',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='X'),
        ),
        migrations.AddField(
            model_name='question',
            name='y_position',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Y'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='interface',
            field=models.CharField(choices=[('DEFAULT', 'Quizzes'), ('MAZE', 'Maze')], default='DEFAULT', max_length=128, verbose_name='Interface'),
        ),
    ]
